<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotePilot.Entity\NotePilot.Entity.csproj" />
    <ProjectReference Include="..\NotePilot.Repository\NotePilot.Repository.csproj" />
  </ItemGroup>

</Project>
